version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.13
      nodejs: 12
    commands:
      - npm install -g serverless@2.0.0
      - npm install
  build:
    commands:
      - make get
      - make test
      - make build
      - export SLS_DEBUG=* && serverless deploy --verbose
