service: tm-game-backend

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  region: eu-west-1

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  helloworld:
    handler: bin/main
    events:
      - http:
          path: helloWorld
          method: get
          cors: true
        


