service: tm-game-backend

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  region: eu-west-1

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  helloworld:
    handler: bin/main
    events:
      - http:
          path: helloWorld
          method: get
          cors: true
  getScore:
    handler: bin/main
    events:
      - http:
          path: getScore
          method: get
          cors: true
  login:
    handler: bin/main
    events:
      - http:
          path: login
          method: post
          cors: true
  directdebits:
    handler: bin/main
    events:
      - http:
          path: directdebits
          method: any
          cors: true
  contactdetails:
    handler: bin/main
    events:
      - http:
          path: contactdetails
          method: get
          cors: true
      - http:
          path: contactdetails
          method: post
          cors: true
      - http:
          path: contactdetails/{type}
          method: put
          cors: true
        


